
export const FETCH_COMMENTS_REDUCER = "FETCH_COMMENTS_REDUCER" 

export const FETCH_COMMENTS_TYPE = "FETCH_COMMENTS_TYPE" 

export const LOGIN_USERS_REDUCER = "LOGIN_USERS_REDUCER" 
export const LOGIN_SUCCESS_REDUCER = "LOGIN_SUCCESS_REDUCER" 
export const LOGIN_FAILED_REDUCER = "LOGIN_FAILED_REDUCER" 





export const LOGIN_USERS_TYPE = "LOGIN_USERS_TYPE" 